
import java.awt.Font;
import java.io.BufferedWriter;
import java.io.FileWriter;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class appbiodata extends javax.swing.JFrame {

    /**
     * Creates new form appbiodata
     */
    public appbiodata() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nmlabel = new javax.swing.JLabel();
        almlabel = new javax.swing.JLabel();
        pkjlabel = new javax.swing.JLabel();
        jklabel = new javax.swing.JLabel();
        codelabel = new javax.swing.JLabel();
        nmbox = new javax.swing.JTextField();
        almbox = new javax.swing.JTextField();
        pkjbox = new javax.swing.JComboBox<>();
        jkbox = new javax.swing.JComboBox<>();
        codebox = new javax.swing.JComboBox<>();
        tampilbutton = new javax.swing.JButton();
        hapusbutton = new javax.swing.JButton();
        simpanbutton = new javax.swing.JButton();
        exitbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nmlabel.setText("Nama");

        almlabel.setText("Alamat");

        pkjlabel.setText("Pekerjaan");

        jklabel.setText("Jenis Kelamin");

        codelabel.setText("Jenis Code");

        pkjbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PNS", "TNI", "Karyawan", "Pengusaha", " " }));

        jkbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));

        codebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tebal", "Miring" }));

        tampilbutton.setText("Tampilkan");
        tampilbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilbuttonActionPerformed(evt);
            }
        });

        hapusbutton.setText("Hapus");
        hapusbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusbuttonActionPerformed(evt);
            }
        });

        simpanbutton.setText("Simpan");
        simpanbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanbuttonActionPerformed(evt);
            }
        });

        exitbutton.setText("Exit");
        exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbuttonActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tampilbutton)
                        .addGap(18, 18, 18)
                        .addComponent(hapusbutton)
                        .addGap(18, 18, 18)
                        .addComponent(simpanbutton)
                        .addGap(18, 18, 18)
                        .addComponent(exitbutton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nmlabel)
                            .addComponent(almlabel)
                            .addComponent(pkjlabel)
                            .addComponent(jklabel)
                            .addComponent(codelabel))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nmbox)
                            .addComponent(almbox)
                            .addComponent(pkjbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jkbox, 0, 106, Short.MAX_VALUE)
                            .addComponent(codebox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(79, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nmlabel)
                    .addComponent(nmbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(almlabel)
                    .addComponent(almbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pkjlabel)
                    .addComponent(pkjbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jklabel)
                    .addComponent(jkbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codelabel)
                    .addComponent(codebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tampilbutton)
                    .addComponent(hapusbutton)
                    .addComponent(simpanbutton)
                    .addComponent(exitbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tampilbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilbuttonActionPerformed
        String nama =  nmbox.getText();
        String alamat = almbox.getText();
        String pekerjaan = (String) pkjbox.getSelectedItem();
        String jeniskelamin = (String) jkbox.getSelectedItem();
        String jeniscetak = (String) codebox.getSelectedItem();
        
        Font tebal = new Font("Arial", Font.BOLD, 12);
        Font miring = new Font("Arial", Font.ITALIC, 12);
        
        if (jeniscetak == "Tebal") {
            jTextArea1.setFont(tebal);
        }
        if (jeniscetak == "Miring") {
            jTextArea1.setFont(miring);
        }
     
        jTextArea1.setText("nama saya "+nama+"\n alamat saya tinggal "+alamat+"\n dengan pekerjaan "+pekerjaan+"\n jenis kelamin saya "+jeniskelamin);
     //jTextArea1.setText("nama saya" + nama "\n alamat saya tinggal " + alamat + "\n dengan pekerjaan " + pekerjaan + "\n jenis kelamin saya " + jeniskelamin) ;
    }//GEN-LAST:event_tampilbuttonActionPerformed

    private void simpanbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanbuttonActionPerformed
        try {
            BufferedWriter out = new BufferedWriter(new FileWriter("penyimpanan.txt"));
            out.write(jTextArea1.getText());
            JOptionPane.showMessageDialog(null, "berhasil disimpan kedalam file");
            out.close();
        } catch (Exception e) {
            System.err.println("Error :" + e.getMessage());
        }
    }//GEN-LAST:event_simpanbuttonActionPerformed

    private void hapusbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusbuttonActionPerformed
        nmbox.setText("");
        almbox.setText("");
        pkjbox.setSelectedItem("PNS");
        jkbox.setSelectedItem("Laki-laki");
        codebox.setSelectedItem("Tebal");
    }//GEN-LAST:event_hapusbuttonActionPerformed

    private void exitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbuttonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appbiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appbiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appbiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appbiodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new appbiodata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField almbox;
    private javax.swing.JLabel almlabel;
    private javax.swing.JComboBox<String> codebox;
    private javax.swing.JLabel codelabel;
    private javax.swing.JButton exitbutton;
    private javax.swing.JButton hapusbutton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> jkbox;
    private javax.swing.JLabel jklabel;
    private javax.swing.JTextField nmbox;
    private javax.swing.JLabel nmlabel;
    private javax.swing.JComboBox<String> pkjbox;
    private javax.swing.JLabel pkjlabel;
    private javax.swing.JButton simpanbutton;
    private javax.swing.JButton tampilbutton;
    // End of variables declaration//GEN-END:variables
}
